# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wMRUFK1Av-41AwwDp3vDIoFPb99-IP8
"""

import matplotlib.pyplot as plt
import numpy as np

xpoints = np.array([0,1,3,6,7,9]);
ypoints= np.array([0,40,50,230,249,250])

plt.plot(xpoints,ypoints ,marker='o')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

ypoints=np.array([1,4,5,7,8,10])

plt.plot(ypoints,marker='o')
plt.show()

from matplotlib.lines import lineStyles
import matplotlib.pyplot as plt
import numpy as np

ypoints=np.array([1,4,2,7,1,10])

plt.plot(ypoints, linestyle='dotted')
plt.plot(ypoints,marker='o')
plt.show()

# labels
import matplotlib.pyplot as plt
import numpy as np

x = np.array([80, 85, 90, 100, 100, 105, 110, 115, 120, 125])
y = np.array([240, 246, 260, 270, 280, 290, 300, 315, 320, 330])

plt.plot(x,y,marker='o')

plt.title("Avarage Cal Count")
plt.xlabel("Average Pulse")
plt.ylabel("Calorie Burnage")

plt.show()

import matplotlib.pyplot as plt
import numpy as np

#plot 1:
x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(1, 2, 1)
plt.plot(x,y)

#plot 2:
x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(1, 2, 2)
plt.plot(x,y)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([35, 25, 25, 15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode = [0.2, 0, 0, 0]

plt.pie(y, labels = mylabels, explode = myexplode, shadow = True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x= np.mean(speed)
y=np.median(speed)
z=stats.mode(speed)
print(x,y,z)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from google.colab import files
uploaded = files.upload()

df= pd.read_csv('Titanic-Dataset.csv')

df.info();

